### PR TITLE
Sections Implemented: Donations, Messages and Language change.

### PR DESCRIPTION
**Pull request by mjimenezleon13**
[WIP] The donate and Message sections front-end in progress.
Page now in spanish.

The idea here is to make a platform that actually helps (at least here in Colombia) while we can implement the language change and the located messages and opportunities to reference them to help where users are.

### CODE REVIEW

**Comment by aristizabal95** [comment]
I'm guessing what's missing is the backend? There's a problem with the footer, the image is not being displayed.

**Comment by mjimenezleon13** [comment]
Yes, what's missing is the back end that links the message section with firebase. I'll take a look a the footer image (it's the github icon plus link here).

**Comment by mjimenezleon13** [comment]
We figured out it was the way in which I was referencing the images. Do you need me to make the appropriate changes?

**Comment by aristizabal95** [comment]
Yes, do the modifications, and change this pull request to push into `next-release`

**Comment by aristizabal95** [comment]
I'm closing this PR so a new one can be opened on the correct branch

**Pull request closed without merging**
